### ISSUE TITLE
Error launching on Ubuntu

### ISSUE THREAD

**Issue by Cavalletta98** [lmstudio-ai/configs#14]
Hi, i'm getting this error on Ubuntu 22:04
`09:19:35.587 › GPU info: '00:02.0 VGA compatible controller: Intel Corporation Device a7a0 (rev 04)'
09:19:35.604 › Got GPU Type: intel
09:19:35.605 › LM Studio: gpu type = Intel
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/local/lib/libclblast.so.1: impossibile aprire il file oggetto condiviso: File o directory non esistente
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1326:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:937:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at 6829 (/tmp/.mount_LM_StuGLW2O1/resources/app/.webpack/main/index.js:2:2077)
    at r (/tmp/.mount_LM_StuGLW2O1/resources/app/.webpack/main/index.js:8:420935)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
^Csimone@simone-ThinkBook-14-G6-IRL:~/Applicazioni$ 
`

**Comment by ricperry** [comment]
I get the following error, also launching on Ubuntu.

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
12:38:12.095 › GPU info: '0c:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] (rev c0)'
12:38:12.102 › Got GPU Type: amd
12:38:12.102 › LM Studio: gpu type = AMD
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/local/lib/libclblast.so.1: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1326:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:937:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at 6829 (/tmp/.mount_LM_StuPZsJwj/resources/app/.webpack/main/index.js:2:1930)
    at r (/tmp/.mount_LM_StuPZsJwj/resources/app/.webpack/main/index.js:8:401969)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

**Comment by Galapagospeed** [comment]
The same issue, today, in Windows 10 with LM-Studio-0.2.10-Setup.exe & LM-Studio-0.2.10-Setup-avx-beta-4.exe, in the middle of the installing progress and also and the same Error at the ending..

![LM-Stud_Error](https://github.com/lmstudio-ai/configs/assets/159195051/ac9730be-246a-4c26-9f93-0a2181025733)

Laptop Asus ASUSTeK COMPUTER INC.
	product			X75A1

Microsoft Windows 10 (10.0) Professional 64-bit   (Build 19045) 
DirectX Version			12.0
Number of cores		2 (max 2)
	Number of threads	2 (max 2)
	Manufacturer		GenuineIntel
	Name			Intel Celeron 1000M
	Codename		Ivy Bridge
	Specification		Intel(R) Celeron(R) CPU 1000M @ 1.80GHz
	Package (platform ID)	Socket 988B rPGA (0x4)
	CPUID			6.A.9
	Extended CPUID		6.3A
	Core Stepping		E1/L1
	Technology		22 nm
	TDP Limit		35.0 Watts
	Tjmax			105.0 �C
	Core Speed		1769.3 MHz
	Multiplier x Bus Speed	18.0 x 98.3 MHz
	Base frequency (cores)	98.3 MHz
	Base frequency (mem.)	98.3 MHz
	Stock frequency		1800 MHz
	Instructions sets	MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, EM64T
	Microcode Revision	0x21
	L1 Data cache		2 x 32 KB (8-way, 64-byte line)
	L1 Instruction cache	2 x 32 KB (8-way, 64-byte line)
	L2 cache		2 x 256 KB (8-way, 64-byte line)
	L3 cache		2 MB (8-way, 64-byte line)
	FID/VID Control		yes
Chipset
-------------------------------------------------------------------------

Northbridge			Intel Ivy Bridge rev. 09
Southbridge			Intel HM70 rev. 04
Bus Specification		PCI-Express 2.0 (5.0 GT/s)
Memory Type			DDR3
Memory Size			12 GBytes
Channels			Dual
Memory Frequency		786.4 MHz (1:6)
CAS# latency (CL)		11.0
RAS# to CAS# delay (tRCD)	11
RAS# Precharge (tRP)		11
Cycle Time (tRAS)		28
Row Refresh Cycle Time (tRFC)	208
Command Rate (CR)		1T
Host Bridge			0x0154


Memory SPD
-------------------------------------------------------------------------

DIMM #				1
	SMBus address		0x52
	Memory type		DDR3L
	Module format		SO-DIMM
	Module Manufacturer(ID)	SK Hynix (AD00000000000000000000000000)
	SDRAM Manufacturer (ID)	SK Hynix (AD00000000000000000000000000)
	Size			8192 MBytes
	Max bandwidth		PC3-12800 (800 MHz)
	Part number		HMT41GS6MFR8C-PB  
	Serial number		35CE8862
	Manufacturing date	Week 33/Year 23
	Number of banks		8
	Nominal Voltage		1.35 Volts
	EPP			no
	XMP			no
	AMP			no
	EXPO			no
JEDEC timings table		CL-tRCD-tRP-tRAS-tRC @ frequency
	JEDEC #1		5.0-5-5-14-19 @ 380 MHz
	JEDEC #2		6.0-6-6-16-22 @ 457 MHz
	JEDEC #3		7.0-7-7-19-26 @ 533 MHz
	JEDEC #4		8.0-8-8-22-30 @ 609 MHz
	JEDEC #5		9.0-9-9-24-33 @ 685 MHz
	JEDEC #6		10.0-10-10-27-37 @ 761 MHz
	JEDEC #7		11.0-11-11-28-39 @ 800 MHz

**Comment by GerritGeeraerts** [comment]
I had a similar error
`ubuntu-22 :: ~/Desktop » ./LM_Studio-0.2.14-beta-1.AppImage 
14:12:07.708 › GPU info: '01:00.0 VGA compatible controller: Intel Corporation Device a780 (rev 04)'
14:12:07.717 › Got GPU Type: intel
14:12:07.718 › LM Studio: gpu type = Intel
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/local/lib/libclblast.so.1: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1326:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:937:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at 6829 (/tmp/.mount_LM_Stukqbuau/resources/app/.webpack/main/index.js:2:2058)
    at r (/tmp/.mount_LM_Stukqbuau/resources/app/.webpack/main/index.js:8:401969)
`

**Comment by k-rol** [comment]
I don't know much about Appimages but to me it seemed like it meant that libclblast.so.1 is not part of the package.
This file is from the [CLBlast library here](https://github.com/CNugteren/CLBlast).

I downloaded the latest release then copied the below 3 within /usr/local/lib with `cp -P ` since both of them are symlinks.

- libclblast.so
- libclblast.so.1
- libclblast.so.1.6.2

It now works for me for the CPU part. Maybe the fact that I get Error Code 256 when trying to offload to the GPU has something to do with the library.
