### ISSUE TITLE
Error when selecting the AI to chat with on ubuntu

### ISSUE THREAD

**Issue by 0Slmpnv0** [lmstudio-ai/configs#17]
I have downloaded mistral instruct, and then tried to chat with it. It returns "(Exit code: 1). Please check settings and try loading the model again. " when i select it. Terminal shows this:
Error: libcuda.so.1: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1326:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:937:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at 4001 (/tmp/.mount_LM_StuIiaazs/resources/app/.webpack/main/utility.js:2:4008)
    at n (/tmp/.mount_LM_StuIiaazs/resources/app/.webpack/main/utility.js:2:594240) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.14.0
[appserver] Error loading model: {
  "cause": "(Exit code: 1). Please check settings and try loading the model again. ",
  "suggestion": "",
  "title": "Model error"
}

**Comment by 0Slmpnv0** [comment]
There is a problem with using GPU. After turning it off everything started working.  I got rtx 4060ti
