### ISSUE TITLE
AMD 7950X3D issue???

### ISSUE THREAD

**Issue by danindiana** [lmstudio-ai/configs#24]
File has permissions to run but upon attempting to run:

./LM_Studio-0.2.14-beta-1.AppImage 
13:05:36.565 › GPU info: '0c:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 164e (rev c9)'
13:05:36.571 › Got GPU Type: amd
13:05:36.571 › LM Studio: gpu type = AMD
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/local/lib/libclblast.so: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1326:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:937:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at 6829 (/tmp/.mount_LM_StuXw6OJ0/resources/app/.webpack/main/index.js:2:1930)
    at r (/tmp/.mount_LM_StuXw6OJ0/resources/app/.webpack/main/index.js:8:401969)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

OS: Ubuntu 22.04 jammy
 Kernel: x86_64 Linux 6.5.0-21-generic
 Uptime: 10m
 Packages: 1762
 Shell: bash 5.1.16
 Resolution: 2560x1080
 DE: GNOME 42.0
 WM: Mutter
 WM Theme: Adwaita
 GTK Theme: Yaru [GTK2/3]
 Icon Theme: Yaru
 Font: Ubuntu 11

node -v
npm -v
v18.19.1
10.2.4

**Comment by shnamin** [comment]
I'm facing the same issue. Has someone looked into this?

**Comment by danindiana** [comment]
> I'm facing the same issue on ubuntu. Has someone looked into this?

LM-studio is now on version 2.18 which may have fixed this issue.
